amazon/urls.py
from django.urls import path
from . import views
from django.contrib import admin

app_name = 'amazon'

urlpatterns = [
    path('lp/', views.Lp.as_view(), name='lp'),
    path('items/', views.ItemList.as_view(), name='item_list'),
    path('item/<int:pk>', views.ItemDetail.as_view(), name='item_detail'),
]

ecsite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('amazon/', include('amazon.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

amazon/models.py
from django.db import models

# Create your models here.


class Product(models.Model):
    class Meta:
        verbose_name = '商品'
        verbose_name_plural = "商品"

    thumbnail = models.ImageField(
        verbose_name='サムネイル',
        upload_to="thumbnails/"
    )

    name = models.CharField(
        verbose_name='名前',
        max_length=150,
        null=False,
        blank=False
    )
    price = models.IntegerField(
        verbose_name='価格'
    )
    description = models.TextField(
        verbose_name='説明'
    )

amazon/views.py
from django.shortcuts import render

# Create your views here.
from django.views import generic
from .models import *


class Lp(generic.TemplateView):
    template_name = 'amazon/lp.html'

    def get_context_data(self, **kwargs):
        context = super(Lp, self).get_context_data(**kwargs)
        all_items = Product.objects.all()
        context['items'] = all_items
        return context


class ItemList(generic.ListView):
    model = Product
    template_name = 'amazon/item_list.html'

    def get_queryset(self):
        products = Product.objects.all()
        if 'q' in self.request.GET and self.request.GET['q'] != None:
            q = self.request.GET['q']
            products = products.filter(name__icontains = q)
        return products


class ItemDetail(generic.DetailView):
    model = Product
    template_name = 'amazon/item_detail.html'

templates/amazon/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css">

        <link href="{% static 'css/base.css' %}" rel="stylesheet" type="text/css"/>
        <link href="{% static 'css/responsive.css' %}" rel="stylesheet" media="only screen and (max-width: 1200px)" />
        <script src="{% static 'js/script.js' %}" type="text/javascript"></script>

        <title>ec amazon</title>
    </head>
    <body>
        <header class="section-header">
            <section class="header-main">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-md-3">
                        <a href="{% url 'amazon:lp' %}">
                            <div class="brand-wrap">
                                <img class="logo" src="{% static 'images/logo-dark.png' %}">
                                <h2 class="logo-text">Techpit amazon</h2>
                            </div> <!-- brand-wrap.// -->
                        </a>
                        </div>
                        <div class="col-lg-6 col-sm-6">
                            <form method= "get" action="{% url 'amazon:item_list' %}" class="search-wrap">
                                <div class="input-group">
                                    <input name="q" type="text" class="form-control" placeholder="Search">
                                    <div class="input-group-append">
                                        <button id="id_search_button" class="btn btn-warning" type="submit">
                                        <i class="fa fa-search"></i>
                                        </button>
                                    </div>
                                </div>
                            </form> <!-- search-wrap .end// -->
                        </div> <!-- col.// -->
                        <div class="col-lg-3 col-sm-6">
                            <div class="widgets-wrap d-flex justify-content-end">

                                <div class="widget-header icontext">
                                    <div class="icon-wrap icon-sm bg2 round text-secondary"><i class="fa fa-user"></i></div>
                                    <div class="text-wrap">
                                        <small>ゲスト</small>
                                    </div>
                                </div> <!-- widget  dropdown.// -->
                            </div>	<!-- widgets-wrap.// -->
                        </div> <!-- col.// -->
                    </div> <!-- row.// -->
                </div> <!-- container.// -->
            </section> <!-- header-main .// -->
        </header> <!-- section-header.// -->
        <div class="container" style="padding: 2rem">
                {% block content %}{% endblock %}
        </div>
        <footer class="section-footer bg2">
            <div class="container">
                <section class="footer-bottom row">

                    <div class="col-sm-12">
                        <p class="text-sm-right">
        Copyright &copy 2019
        <a href="#">Techpit</a>
                        </p>
                    </div>
                </section> <!-- //footer-top -->
            </div><!-- //container -->
        </footer>

         {% block scripts %}{% endblock %}
    </body>
</html>

templates/amazon/item_detail.html
{% extends "amazon/base.html" %}
{% block content %}
{% load static %}

<main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">
        <div class="row wow fadeIn">
            <div class="col-md-6 mb-4">
                <img src="{{ object.thumbnail.url }}" class="img-fluid" alt="">
            </div>
            <div class="col-md-6 mb-4">
                <div class="p-4">
                    <div class="mb-3">
                        <a href="">
                        <span class="badge purple mr-1">Category 2</span>
                        </a>
                        <a href="">
                        <span class="badge blue mr-1">New</span>
                        </a>
                        <a href="">
                        <span class="badge red mr-1">Bestseller</span>
                        </a>
                    </div>
                    <p class="lead">
                        <h2>{{ object.name }}</h2>
                        <span>¥{{ object.price }}</span>
                    </p>
                    <p class="lead font-weight-bold">商品説明</p>
                    <p>{{ object.description }}</p>
                </div>
            </div>
        </div>
        <hr>
        <div class="row d-flex justify-content-center wow fadeIn">

            <div class="col-md-6 text-center">

                <h4 class="my-4 h4">Additional information</h4>

                <p>
                    Djangoのようなフレームワークを利用しても、ページのデザインを綺麗にすることはできません。
                    恐らくこの教材で学習している方のほとんどがどちらかというとサーバサイドを勉強している方が多いのかと思慮しますので、
                    htmlやcssの部分はあまり得意でないという方が多いと思います。そのような方はぜひBootstrap等のCSSフレームワークを利用することをお勧めします。
                    また、コードのスニペットをネット上から拝借するのも非常に良いと思います。日本の
                    サイトですとまだこのスニペットのまとめサイトのようなものは少ないですが、海外ですと無数に存在するので、ぜひそれらを活用していただくことをお勧めします。(無料で公開されていることろが多いです)
                    特にログイン画面やサインアップ部分は「bootstrap login snippet」等で検索するといろいろな方が作成したスニペットが出てくるので、是非今後「自分でサービス開発したい！」となった際にご参考にしていただければと思います。
                </p>
            </div>
        </div>
        <div class="row wow fadeIn">
            <div class="col-lg-4 col-md-12 mb-4">
                <img src="https://techpit-market-prod.s3.amazonaws.com/uploads/part_attachment/file/3695/b76122f9-c56b-4920-9634-03ea1e95855a.jpg" class="img-fluid" alt="">

            </div>
            <div class="col-lg-4 col-md-6 mb-4">
                <img src="https://techpit-market-prod.s3.amazonaws.com/uploads/part_attachment/file/3696/2124690a-14c9-450c-93ea-28a97c3f4e38.jpg" class="img-fluid" alt="">
            </div>
            <div class="col-lg-4 col-md-6 mb-4">
                <img src="https://techpit-market-prod.s3.amazonaws.com/uploads/part_attachment/file/3697/f78b1352-20d8-48c3-9d60-1c5c92a137c6.jpg" class="img-fluid" alt="">

            </div>
        </div>
    </div>
</main>   
{% endblock %}

templates/amazon/item_list.html
{% extends "amazon/base.html" %}
{% block content %}
{% load static %}
    <div class="row-sm">
    {% for object in object_list %}
        
        <div class="col-md-3">
            <figure class="card card-product">
                <div class="img-wrap"> <img src="{{ object.thumbnail.url }}"></div>
                    <figcaption class="info-wrap">
                        <h6 class="title "><a href="{% url 'amazon:item_detail' object.pk %}">{{ object.name }}</a></h6>
                        
                        <div class="price-wrap">
                            <span class="price-new">{{ object.price }}円</span>
                        </div> <!-- price-wrap.// -->
                    
                </figcaption>
            </figure> <!-- card // -->
        </div> <!-- col // -->
        
    {% endfor %}
    </div>
{% endblock %}

templates/amazon/lp.html
<!-- [2-5] ベーステンプレート読み込み追加　ここから -->
{% extends "amazon/base.html" %}
{% block content %}
{% load static %}
    <link href="{% static 'plugins/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
    <link href="{% static 'plugins/owlcarousel/assets/owl.theme.default.css' %}" rel="stylesheet">
    <script src="{% static 'plugins/owlcarousel/owl.carousel.min.js' %}"></script>
  
    <section class="section-main bg padding-top-sm">
        <div class="container">
            <div class="row-sm">
                <div class="col-md-12">
                   <div class="owl-init slider-main owl-carousel" data-items="1" data-dots="false" data-nav="true">
                       {% for item in items %}
                        <div class="item-slide">
                            <img src="{{ item.thumbnail.url }}">
                        </div>
                       {% endfor %}
                    </div>
                </div> <!-- col.// -->
            </div>
            <div class="mb-3">
                <div class="owl-init slider-main owl-carousel" data-items="1" data-dots="false" data-nav="true">
                    {% for item in items %}
                        <a href="{% url 'amazon:item_detail' item.pk %}">
                            <img class="img-sm" style="width: 100px;" src="{{ item.thumbnail.url }}">
                        </a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>
    <section class="section-content padding-y bg">
        <div class="container">
        
            <div class="card">
                <div class="card-body">
            
                    <header class="section-heading">
                        <h3 class="title-section">Django Amazon</h3>
                    </header>
                    
                    <article>
                        <p>
                            この教材ではDjangoを用いてAmazonに代表されるECサイトを作成します。Djangoが提供する多くの機能の中でも、主にCBV（クラスベースビュー）を
                            積極的に用いて、書くコードの量をなるべく減らすような設計にしております。Djangoを利用すると言っても同じ機能を実現させるさせるために様々な手段がありますので、
                            この教材が紹介しているやり方が正解だとは思わず、選択肢の一つとして受け入れていただければと思います。
                            人のやり方やコードをうまく取り入れる（パクる）ことが、実務をこなせるレベルになる最短ルートだと私は考えておりますので、
                            是非ここで学んだ実装方法を積極的に活用いただけると嬉しいです。
                        </p> 
                    </article>
                </div>
            </div>
        
        </div> <!-- container .//  -->
    </section>
{% endblock %}
<!-- [2-5] ベーステンプレート読み込み追加　ここまで -->